# Generated by Django 4.0.4 on 2022-09-20 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_alter_subcategory_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='subCategory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
