# Generated by Django 3.2.15 on 2022-09-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_auto_20220921_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('raised', 'raised'), ('processing', 'processing'), ('closed', 'closed')], max_length=100),
        ),
    ]
