# Generated by Django 3.2.15 on 2022-09-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
