# Generated by Django 3.2.15 on 2022-09-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ps_number',
            field=models.IntegerField(unique=True),
        ),
    ]
